language: android

sudo: false

android:
    components:
        # Use the latest SDK build tools
        - platform-tools
        - tools

        # The BuildTools version used by your project
        - build-tools-23.0.2

        # The SDK version used to compile your project
        - android-19
        - android-23

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-19

        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        #- sys-img-armeabi-v7a-android-19
        - sys-img-armeabi-v7a-android-23

# Emulator Management: Create, Start and Wait
before_install:
    - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    
before_script:
    - android list targets
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
